### ISSUE TITLE
Securing Parachain Code Integrity through Verifiable Builds

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#346]
**As a** LAOS community member involved in both using and governing the parachain,  
**I want** a verifiable and transparent process that assures the parachain's code matches the official repository on GitHub, and to confirm that any runtime upgrades are the exact code I can verify and compile,  
**so that** the integrity of the parachain's operations is maintained, fostering trust within the community and safeguarding against unauthorized modifications.

## Acceptance Criteria

1. **Detailed Verification Metadata**: Each release must include a comprehensive set of metadata similar to the Polkadot SDK example, including runtime size, version, and various cryptographic hashes.

![Image](https://github.com/freeverseio/laos/assets/2387339/c2062be1-51f7-43be-8e50-82f17ed22bb0)

**Comment by asiniscalchi** [comment]
We are going to achive it using srtools ...

**Comment by asiniscalchi** [comment]
**IMPORTANT** it will possible to generate a release from any tag in main branch.

**Comment by ccubu** [comment]
Here at this link it can be seen that the release job proposed to merge works on every tag, but only checks for correct version on tags that start with "v*".

Also wasm build times average 20 minutes.

https://github.com/ccubu/laos/releases

**Comment by ccubu** [comment]
Since there isn't quorum on creating a fake release to test it, we can still verify this task by taking a look at the following resources:

- The process of updating the release description and artifacts can be verified by taking a look at this forked repository releases: https://github.com/ccubu/laos/releases

- The rest of the release workflow can be checked on this failed workflow that highlights how the wasm had been build with srtool and the docker image is pushed correctly, but it fails when trying to update a release that does not exist. https://github.com/freeverseio/laos/actions/runs/8186415496/job/22384771376?pr=395

**Comment by ccubu** [comment]
Had a permission error trying to create a release from a hotfix
<img width="1041" alt="image" src="https://github.com/freeverseio/laos/assets/60666948/266eca70-fb59-42b5-8b5c-6c205a229cc5">

**Comment by dastanfv** [comment]
https://github.com/freeverseio/laos/releases/tag/v0.12.1 -> working
