### ISSUE TITLE
Ensuring Two Years of Support for Block Producers from the RewardsAccount

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#363]
**As a** RewardsAccount holder with 150M tokens,  
**I want** the block producers of my parachain to be rewarded with tokens from the RewardsAccount,  
**so that** the Rewards Account can sustainably distribute rewards and last at least 2 years.

# Acceptance Criteria

1. **Inflation Control**: The network has 0 inflation.
2. **Sustainable Reward Distribution**: The distribution mechanism must ensure that the RewardsAccount is capable of distributing rewards to the block producer of the parachain for at least 2 years without depleting the funds.
3. **Delegator rewards**: Overview of the algorithm of delegator rewards.

![Image](https://github.com/freeverseio/laos/assets/2387339/c26a2ce6-ae51-4a18-99c6-de739e59916e)

**Comment by ccubu** [comment]
After discussing with the team we summarized here the points we have agreed upon regarding this task.

1. With the current kilt implementation the only thing we can achieve is configuring it to allocate giving away a maximum of 75M yearly
 - Con: This means that the rewards are not fixed nor constant per block, and the 75M yearly will only be given if the max amount of stakers and stake is reached.
 - Pro: We don't change kilt staking pallet implementation we only configure it via it's values.

2. If we wish to give away 75M yearly no matter the amount of stakers/collators/delegators we need another implementation, via refactoring the kilt pallet, via making a new pallet ourselves or by finding another pallet that allows us to fix rewards.

**Comment by asiniscalchi** [comment]
/// Handler to distribute a collator's reward.
/// To use the default implementation of minting rewards, specify the type `()`.
type PayoutCollatorReward: PayoutCollatorReward<Self>;

**Comment by asiniscalchi** [comment]
**IMPORTANT** we  also might add test to ParachainStakingAdapter

**Comment by asiniscalchi** [comment]
```
        "inflationConfig": {
          "expect": {
            "min": 100000000000000000000000,
            "ideal": 200000000000000000000000,
            "max": 500000000000000000000000
          },
          "annual": {
            "min": 72000000,
            "ideal": 72000000,
            "max": 72000000
          },
          "round": {
            "min": 0,
            "ideal": 0,
            "max": 0
          }
        },
```
That's the proposed inflation config. 
The annual inflation rate is 7.2% that compounded will reach 7.5%
----
the expect set are for the desired staking amount .. they are not affecting the calculation of the rewards because the annual inflation is fixed, however they are copied from the Moonbeam configuration

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos/issues/428

**Comment by asiniscalchi** [comment]
It appears that the LAOS runtime is not triggering the reward distribution event for block producers. This issue has been observed in the [LAOS Sun Test Network explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.laossun.gorengine.com#/explorer); no events related to rewards are being logged.

**Acceptance Criteria:**
1. Identify and fix the root cause of the missing reward event.
2. Ensure the reward distribution event is logged in the blockchain explorer.
3. Validate that rewards are properly allocated and distributed to block producers.

**Priority:** High - This affects the block producer's incentives and the correct function of the blockchain.



![Image](https://github.com/freeverseio/laos/assets/2387339/8029c9fb-4edf-413b-92fd-de26e99aa8e3)

**Comment by asiniscalchi** [comment]
we want the following events to be emitted:


![Image](https://github.com/freeverseio/laos/assets/2387339/761f110f-f3c6-410c-a1e0-7be653e56af1)



![Image](https://github.com/freeverseio/laos/assets/2387339/de48f844-c12f-463c-b500-9286ac150935)

**Comment by ccubu** [comment]
Scenario 3 collators staking 20k and 1 delegator on collator-0 delegatin 20k

For this round the rewards were given as follows:
Col-0 28.4
delegator 1 delegating in col-0 28.4

col-1 56.8

col-2 28.4

The col-1 was lucky to produce more blocks in the round

The following images can be used to corroborate the rewards paid.

![Image](https://github.com/freeverseio/laos/assets/60666948/ed541c75-295b-470c-8157-68d08a089227)



![Image](https://github.com/freeverseio/laos/assets/60666948/befa0a7c-66d9-4fbb-9a0c-a14aa8486d61)
