### ISSUE TITLE
Expose Moonbeam-like Staking API for EVM

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#536]
**As a** developer,
**I want** to expose an API equivalent to Moonbeam's for staking in the EVM,
**so that** users can interact with staking functionalities seamlessly through our EVM interface.

### Acceptance Criteria
1. **Functional Parity**
   - The API should provide functional parity with Moonbeam’s staking API.
   - Ensure that all core staking functionalities (delegation, undelegation, reward claiming, etc.) are supported.
2. **Use Moonbeam precompile**: it's audited, so we want to use it as it is (if possible): https://github.com/moonbeam-foundation/moonbeam/tree/master/precompiles/parachain-staking

### Notes

- Refer to Moonbeam's official documentation for specific details on their staking API.
- Ensure compatibility with our existing EVM infrastructure.

**Comment by asiniscalchi** [comment]
**As a** developer,
**I want** to expose an API equivalent to Moonbeam's for staking in the EVM,
**so that** users can interact with staking functionalities seamlessly through our EVM interface.

### Acceptance Criteria
1. **Functional Parity**
   - The API should provide functional parity with Moonbeam’s staking API.
   - Ensure that all core staking functionalities (delegation, undelegation, reward claiming, etc.) are supported.

2. **Testing**
   - Comprehensive unit and integration tests should be written to validate API functionality.
   - Perform security testing to ensure the API is robust against common vulnerabilities.

### Notes

- Refer to Moonbeam's official documentation for specific details on their staking API.
- Ensure compatibility with our existing EVM infrastructure.

**Comment by magecnion** [comment]
gas estimation bug: https://github.com/freeverseio/laos/issues/695
