### ISSUE TITLE
Increase MaxSchedulerPerBlock for Benchmarking

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#840]
As a developer, I want to increase the MaxSchedulerPerBlock parameter when running benchmarks to align with best practices used in the polkadot-sdk.

> *"We recommend increasing the MaxSchedulerPerBlock parameter when running benchmarks, as done in the polkadot-sdk default node runtime."*

**Comment by luispdm** [comment]
Polkadot-sdk example -> https://github.com/paritytech/polkadot-sdk/blob/master/substrate/bin/node/runtime/src/lib.rs#L457-L460

**Comment by ccubu** [comment]
I think this error might not be directly caused by the change in this PR but I am unable to run all the benchmarks.

Pallet_democracy::veto_external fails with a Bad origin error as can be seen on the logs attached.

[benchmarking_errors.txt](https://github.com/user-attachments/files/17587101/benchmarking_errors.txt)

**Comment by luispdm** [comment]
It's unrelated; I just tested on a branch that doesn't have this change

**Comment by ccubu** [comment]
Created this task to fix the benchmark error to tackle in the future https://github.com/orgs/freeverseio/projects/3/views/7?filterQuery=no%3Astatus+no%3Asprint+benchma&pane=issue&itemId=85837117
